# Generated by Django 3.1.7 on 2021-03-25 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210325_1557'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subscriber',
            table='subscriber',
        ),
    ]
