# Generated by Django 3.1.7 on 2021-03-21 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20210321_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cate_id', models.AutoField(primary_key=True, serialize=False)),
                ('cate_name', models.TextField()),
                ('cate_img', models.CharField(max_length=255)),
                ('cate_status', models.IntegerField()),
                ('cate_detail', models.TextField()),
                ('cate_img1', models.CharField(max_length=255)),
                ('cate_img2', models.CharField(max_length=255)),
                ('cate_img3', models.CharField(max_length=255)),
                ('cate_img4', models.CharField(max_length=255)),
                ('cate_description', models.TextField()),
                ('cate_body', models.TextField()),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
    ]
